apiVersion: v1
kind: Service
metadata:
  name: plutus-api
  labels:
    app: plutus-api
spec:
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 3000
  selector:
    app: plutus-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: plutus-api
  labels:
    app: plutus-api
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: plutus-api
      version: v1
  template:
    metadata:
      labels:
        app: plutus-api
        version: v1
    spec:
      containers:
      - name: plutus-api
        image: odiosdado/oddevs:plutus-api-18
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
        env:
          - name: MONGODB_URI
            value: "mongodb://plutus-db:27017"
          - name: MONGODB_USER
            value: "plutus"
          - name: MONGODB_PASS
            value: "Testing123"
          - name: JWT_SECRET
            value: "2vEp9koTrc32eCKubPOafUuokkTVt3KMFCUd8DXp2IHRVh7X"
          - name: FACEBOOK_CLIENT_ID
            value: "1263168497215067"
          - name: FACEBOOK_CLIENT_SECRET
            value: "ab5195d6da92e987e8044518073b71ad"
          - name: FACEBOOK_CALLBACK_URL
            value: "http://localhost:3000/v1/auth/facebook/callback"
          - name: FACEBOOK_PROFILE_URL
            value: "https://graph.facebook.com/v2.5/me?fields=first_name,last_name,email"
          - name: GOOGLE_CLIENT_ID
            value: "552080757919-gkhnfd2s13klqf4316mimn3mecker32s.apps.googleusercontent.com"
          - name: GOOGLE_CLIENT_SECRET
            value: "485GU9JMfVKcMSM2lxqXwpXy"
          - name: GOOGLE_CALLBACK_URL
            value: "http://localhost:3000/v1/auth/google/callback"
          - name: LOGGER_LEVEL
            value: "debug"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: plutus-api
spec:
  hosts:
  - api.plutus.oddevs.com
  gateways:
  - istio-system/oddevs-gateway # define gateway name
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: plutus-api # Backend service name
        port:
          number: 80 # Backend service port