apiVersion: v1
kind: Service
metadata:
  name: plutus-api
  labels:
    app: plutus-api
spec:
  ports:
  - port: 80
    name: http
  selector:
    app: plutus-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: plutus-api
  labels:
    app: plutus-api
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: plutus-api
      version: v1
  template:
    metadata:
      labels:
        app: plutus-api
        version: v1
    spec:
      containers:
      - name: plutus-api
        image: odiosdado/oddevs:plutus-api-5
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        env:
          - name: PLUTUS_JDBC_URL
            value: "jdbc:mysql://plutus-db/plutus?autoReconnect=true&useSSL=false"
          - name: PLUTUS_JDBC_USER
            value: "svcplutus"
          - name: PLUTUS_JDBC_PASS
            value: "N00dle1234"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: plutus-api
spec:
  hosts:
  - api.plutus.oddevs.com
  gateways:
  - istio-system/oddevs-gateway # define gateway name
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: plutus-api # Backend service name
        port:
          number: 80 # Backend service port